version: '3.8'
services:
  stash-db:
    image: mongo:latest
    container_name: stash-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: stash_db
    volumes:
      - stash_mongo_data:/data/db
volumes:
  stash_mongo_data: